# https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles
# https://snakemake.readthedocs.io/en/stable/executing/cluster.html#executing-on-slurm-clusters
# https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#snakefiles-resources
# https://www.embl.org/groups/bioinformatics-rome/blog/2022/04/snakemake-profile-4-defining-resources-and-threads/
slurm: True
jobs: 1000
latency-wait: 60
quiet: progress
keep-going: True
rerun-incomplete: True
default-resources:
  - slurm_account=es_biol
  - slurm_partition=es_biol
  - threads=1
  - mem_mb_per_cpu=1024
  - runtime=30
set-resources:
  # smina/gnina (docking): 64 threads, 16G mem, 8hrs runtime
  - smina:threads=64
  - smina:mem_mb_per_cpu=256
  - smina:runtime=480
  - gnina:threads=64
  - gnina:mem_mb_per_cpu=256
  - gnina:runtime=480
