#!/usr/bin/env bash
#https://scicomp.ethz.ch/wiki/LSF_to_Slurm_quick_reference
export XDG_CACHE_HOME="$(pwd)/_smk_sbatch/source_cache"
TIMESTAMP=$(date +"%y-%m-%d_%H%M")
mkdir -p _smk_sbatch/logs/$TIMESTAMP
time snakemake $@ --jobs 100 --local-cores $SLURM_NTASKS --latency-wait 60 --use-conda --cluster "sbatch \
--account=es_biol --partition=es_biol \
--ntasks=64 \
--mem-per-cpu=256 \
--time=8:00:00 \
--job-name={rule} \
--output=_smk_sbatch/logs/$TIMESTAMP/%J_{rule}.stdout.txt \
--error=_smk_sbatch/logs/$TIMESTAMP/%J_{rule}.stderr.txt \
"
